image: docker.io/library/golang:1.22

definitions:
  steps:
  - step: &build-push
      name: build-push
      oidc: true
      script:
      - docker build --file Containerfile --tag cluster-api-provider-cloud-director-tenant:${BITBUCKET_COMMIT} .
      - pipe: atlassian/aws-ecr-push-image:2.3.0
        variables:
          AWS_DEFAULT_REGION: eu-north-1
          AWS_OIDC_ROLE_ARN: arn:aws:iam::075899289117:role/BitbucketPipelinesClusterApiProviderCloudDirectorTenant
          IMAGE_NAME: cluster-api-provider-cloud-director-tenant
          TAGS: ${BITBUCKET_COMMIT}

pipelines:
  default:
  - step: *build-push
