apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- clusterrolebinding.yaml
- deployment.yaml
- serviceaccount.yaml
images:
- name: controller
  newName: 075899289117.dkr.ecr.eu-north-1.amazonaws.com/cluster-api-provider-cloud-director-tenant
  newTag: abc123
