//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"sigs.k8s.io/cluster-api/api/v1beta1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantCluster) DeepCopyInto(out *CloudDirectorTenantCluster) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantCluster.
func (in *CloudDirectorTenantCluster) DeepCopy() *CloudDirectorTenantCluster {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantCluster)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDirectorTenantCluster) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantClusterList) DeepCopyInto(out *CloudDirectorTenantClusterList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudDirectorTenantCluster, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantClusterList.
func (in *CloudDirectorTenantClusterList) DeepCopy() *CloudDirectorTenantClusterList {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantClusterList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDirectorTenantClusterList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantClusterSpec) DeepCopyInto(out *CloudDirectorTenantClusterSpec) {
	*out = *in
	out.ControlPlaneEndpoint = in.ControlPlaneEndpoint
	if in.IdentityRef != nil {
		in, out := &in.IdentityRef, &out.IdentityRef
		*out = new(CloudDirectorTenantIdentityRef)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantClusterSpec.
func (in *CloudDirectorTenantClusterSpec) DeepCopy() *CloudDirectorTenantClusterSpec {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantClusterSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantClusterStatus) DeepCopyInto(out *CloudDirectorTenantClusterStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantClusterStatus.
func (in *CloudDirectorTenantClusterStatus) DeepCopy() *CloudDirectorTenantClusterStatus {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantClusterStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantIdentityRef) DeepCopyInto(out *CloudDirectorTenantIdentityRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantIdentityRef.
func (in *CloudDirectorTenantIdentityRef) DeepCopy() *CloudDirectorTenantIdentityRef {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantIdentityRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachine) DeepCopyInto(out *CloudDirectorTenantMachine) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachine.
func (in *CloudDirectorTenantMachine) DeepCopy() *CloudDirectorTenantMachine {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachine)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDirectorTenantMachine) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineList) DeepCopyInto(out *CloudDirectorTenantMachineList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudDirectorTenantMachine, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineList.
func (in *CloudDirectorTenantMachineList) DeepCopy() *CloudDirectorTenantMachineList {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDirectorTenantMachineList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineSpec) DeepCopyInto(out *CloudDirectorTenantMachineSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineSpec.
func (in *CloudDirectorTenantMachineSpec) DeepCopy() *CloudDirectorTenantMachineSpec {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineStatus) DeepCopyInto(out *CloudDirectorTenantMachineStatus) {
	*out = *in
	if in.Addresses != nil {
		in, out := &in.Addresses, &out.Addresses
		*out = make([]v1beta1.MachineAddress, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineStatus.
func (in *CloudDirectorTenantMachineStatus) DeepCopy() *CloudDirectorTenantMachineStatus {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineTemplate) DeepCopyInto(out *CloudDirectorTenantMachineTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineTemplate.
func (in *CloudDirectorTenantMachineTemplate) DeepCopy() *CloudDirectorTenantMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDirectorTenantMachineTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineTemplateList) DeepCopyInto(out *CloudDirectorTenantMachineTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CloudDirectorTenantMachineTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineTemplateList.
func (in *CloudDirectorTenantMachineTemplateList) DeepCopy() *CloudDirectorTenantMachineTemplateList {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CloudDirectorTenantMachineTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineTemplateResource) DeepCopyInto(out *CloudDirectorTenantMachineTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineTemplateResource.
func (in *CloudDirectorTenantMachineTemplateResource) DeepCopy() *CloudDirectorTenantMachineTemplateResource {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CloudDirectorTenantMachineTemplateSpec) DeepCopyInto(out *CloudDirectorTenantMachineTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CloudDirectorTenantMachineTemplateSpec.
func (in *CloudDirectorTenantMachineTemplateSpec) DeepCopy() *CloudDirectorTenantMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(CloudDirectorTenantMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}
